In [2]:
import numpy as np

#create arrays using numpy

#1d array

arr1 = np.array([1,2,3,4,5,])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [3]:
arr2 = np.array([1,2,3,4,5,])
arr2.reshape((1,5)) #1 row and 5 columns


array([[1, 2, 3, 4, 5]])

In [4]:
arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [21]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [6]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
 ## identity matrix

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
#attributes of NP array
arr = np.array([[1,2,3],[4,5,6]])

print("Array: \n", arr)
print("shape:", arr.shape)
print("size of elelments numbers:", arr.size)
print("data type:", arr.dtype)
print("item size:", arr.itemsize)

Array: 
 [[1 2 3]
 [4 5 6]]
shape: (2, 3)
size of elelments numbers: 6
data type: int64
item size: 8


In [9]:
# numpy vectorized operations

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

#element wise addition

print("addition : ", arr1+arr2)

#subtration
print("substraction : ", arr1-arr2)

#multiplication
print("substraction : ", arr1*arr2)

print("division : ", arr1/arr2)


addition :  [11 22 33 44 55]
substraction :  [ -9 -18 -27 -36 -45]
substraction :  [ 10  40  90 160 250]
division :  [0.1 0.1 0.1 0.1 0.1]


In [10]:
#universal function that applies on whole array

arr = np.array([2,3,4,5,6])
#sqrt
print(np.sqrt(arr))
#exponential
print(np.exp(arr))

#sine
print(np.sin(arr))

#log 
print(np.log(arr))


[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [24]:
#array slicing and indexing 
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array: \n", arr, "\n array shape :\n",arr.shape)

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 
 array shape :
 (3, 4)


In [12]:
arr[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

In [13]:
print(arr[0][0])
print(arr[0:2,2:])


1
[[3 4]
 [7 8]]


In [14]:
#take 7 8 11 12

arr[:,2:]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

In [15]:
#modify array elelments
arr[0][0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [16]:
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [25]:
#statistical conectp - Normalization
#change the data to have a mean of 0 and std of 1

data = np.array([1,2,3,4,5])

#calculate the mean
mean = np.mean(data)
std_dev = np.std(data)

#normalize the data
normalized_data = (data-mean)/std_dev

print("normalized data: \n", normalized_data)

normalized data: 
 [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [29]:
#logical operations

data=np.array([1,2,3,4,5,6,7,8,9,10])

data[(data>5)& (data>8)]

array([ 9, 10])